#!/usr/bin/env bash

DATAFILE=${DATAFILE:=data.pbf}

echo "----------"
echo "Update started: `date +%c`"

# update
rm change.osc.gz
osmupdate $DATAFILE change.osc.gz
if [ ! -s change.osc.gz ]; then
	echo "Failed to update data"
	exit
fi
# apply & clip
osmconvert $DATAFILE change.osc.gz -B=bounds.poly --complete-ways --complex-ways --out-o5m > temp.o5m
osmconvert $DATAFILE temp.o5m --diff > change.osc

osmconvert temp.o5m --out-pbf > temp.pbf && \
mv temp.pbf data.pbf

if [ $? -ne 0 ]; then
	exit
fi

rm temp.o5m
md5sum $DATAFILE > $DATAFILE.md5

